### ISSUE TITLE
Если класс описывает однотипные объекты, то он должен называться в единственном числе, т.е. Product

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework4Ozon#1]
https://github.com/HelgaJava/git-homework4Ozon/blob/2a0115e48e4bb84c87fa40600da6009a0fa952e1/src/main/java/ru/itpark/Products.java#L3

**Comment by HelgaJava** [comment]
а в Main массив, также в единственном числе или оставить множественное, т.к. там же много элементов?

**Comment by HelgaJava** [comment]
изменила название класса, название массива оставила во множественном числе
